import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { InstallPWA } from "../components/download-btn";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [imageSource, setImageSource] = useState("");
  const [videoSource, setVideo] = useState("");

  const handleCapture = (type) => (event) => {
    const files = event?.target?.files ?? [];

    if (files.length) {
      const file = files[0];
      const newUrl = URL.createObjectURL(file);
      type === "image" ? setImageSource(newUrl) : setVideo(newUrl);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>POC Blue-Camera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <InstallPWA />
        <br />
        <h5>Prueba de concepto - Camara</h5>
        {imageSource && (
          <div>
            <Image src={imageSource} alt={"snap"} width={200} height={200} />
          </div>
        )}
        <p>Sacar una foto</p>
        <input
          accept="image/*"
          id="icon-button-file"
          type="file"
          capture="environment"
          onChange={handleCapture('image')}
        />
        {videoSource && (
          <div>
            <video src={videoSource} width={200} height={200} controls/>
          </div>
        )}
        <p>Hacer un video</p>
        <input
          accept="video/*"
          id="icon-button-file"
          type="file"
          capture="environment"
          onChange={handleCapture('video')}
        />
      </div>
    </div>
  );
}
